/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 로그아웃 */
    post: operations["AuthController_logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/signIn": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이메일+비밀번호 로그인 */
    post: operations["AuthController_signIn"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/signUp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 이메일+비밀번호 회원가입 */
    post: operations["AuthController_signUp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 토큰 재발급 */
    post: operations["AuthController_token"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hello": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 키와 매칭되는 사용자 정보 변경 API */
    patch: operations["UsersController_update"];
    trace?: never;
  };
  "/api/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 로그인 사용자 정보 */
    get: operations["UsersController_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/widgets/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 워크스페이스 위젯 목록 조회 */
    get: operations["WidgetsController_findAllByWidgetWorkspace"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 삭제된 워크스페이스 목록 */
    get: operations["WorkspacesController_findManyByDeleted"];
    put?: never;
    /** 워크스페이스 생성 */
    post: operations["WorkspacesController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 워크스페이스 단건 조회 */
    get: operations["WorkspacesController_findOne"];
    put?: never;
    post?: never;
    /** 워크스페이스 삭제 (soft delete) */
    delete: operations["WorkspacesController_remove"];
    options?: never;
    head?: never;
    patch: operations["WorkspacesController_update"];
    trace?: never;
  };
  "/api/v1/workspaces/{id}/favorite": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 워크스페이스 즐겨찾기 */
    patch: operations["WorkspacesController_favorite"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthEntity: {
      /**
       * Format: date-time
       * @description 만료일
       */
      expiresAt: string;
      /**
       * @description 만료시간
       * @example 30m
       */
      expiresIn: string;
      /** @description Refresh 토큰 */
      refreshToken: string;
      /**
       * @description 토큰
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
       */
      token: string;
      /**
       * @description 토큰타입
       * @example Bearer
       */
      tokenType: string;
      /** @description 세션 유저 정보 */
      user: components["schemas"]["UserEntity"];
    };
    AuthResponseDto: {
      /** @description 데이터 응답 */
      data: components["schemas"]["AuthEntity"];
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    CreateWorkspaceDto: {
      /**
       * 워크스페이스 설명
       * @description 워크스페이스에 대한 설명
       * @example This is my workspace
       */
      description?: string | null;
      /**
       * 워크스페이스 이름
       * @description 워크스페이스를 대표하는 이름
       * @example My Workspace
       */
      title: string;
    };
    FavoriteWorkspaceDto: {
      /**
       * @description 즐겨찾기 여부
       * @example true
       */
      isFavorite: boolean;
    };
    HttpErrorDto: {
      /** @description Http Exception Response DTO */
      error: components["schemas"]["HttpExceptionResponseDto"];
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    HttpExceptionResponseDto: {
      /**
       * @description 에러명
       * @enum {string}
       */
      error:
        | "BadRequestException"
        | "ForbiddenException"
        | "NotFoundException"
        | "UnauthorizedException"
        | "NotAcceptableException"
        | "RequestTimeoutException"
        | "ConflictException"
        | "GoneException"
        | "HttpVersionNotSupportedException"
        | "PayloadTooLargeException"
        | "UnsupportedMediaTypeException"
        | "UnprocessableEntityException"
        | "InternalServerErrorException"
        | "NotImplementedException"
        | "ImATeapotException"
        | "MethodNotAllowedException"
        | "BadGatewayException"
        | "ServiceUnavailableException"
        | "GatewayTimeoutException"
        | "PreconditionFailedException"
        | "ThrottlerException";
      /** @description 에러메시지 */
      message: string;
    };
    LogoutResponseDto: {
      /** @description 데이터 응답 */
      data: boolean;
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    PageInfoDto: {
      /** @description 현재 페이지 */
      currentPage: number;
      /** @description 다음 페이지 존재 여부 */
      hasNextPage: boolean;
      /** @description 다음 페이지 번호 */
      nextPage: number | null;
    };
    RoleEntity: {
      /**
       * 기호
       * @description 역할 기호
       * @example USER
       */
      symbol: string;
    };
    SignInDTO: {
      /**
       * Email
       * @description 이메일 주소
       * @example example@example.com
       */
      email: string;
      /**
       * Password
       * @description The password of the user
       */
      password: string;
      /**
       * Provider
       * @description 인증 방식
       * @example email
       * @enum {string}
       */
      provider: "email";
    };
    SignUpDTO: {
      /**
       * Email
       * @description 이메일 주소
       * @example example@example.com
       */
      email: string;
      /**
       * Password
       * @description The password of the user
       */
      password: string;
      /**
       * Provider
       * @description 인증 방식
       * @example email
       * @enum {string}
       */
      provider: "email";
      /**
       * Usernaem
       * @description 유저의 이름
       * @example John Doe
       */
      username?: string | null;
    };
    TokenDTO: {
      /**
       * 재발급 토큰
       * @description 재발급 토큰
       */
      refreshToken: string;
    };
    UpdateUserDto: {
      /**
       * 이미지
       * @description 프로필 이미지
       * @example https://example.com/image.jpg
       */
      image?: string | null;
      /**
       * Usernaem
       * @description 유저의 이름
       * @example John Doe
       */
      username?: string | null;
    };
    UpdateWorkspaceDto: {
      /**
       * 워크스페이스 설명
       * @description 워크스페이스에 대한 설명
       * @example This is my workspace
       */
      description?: string | null;
      /**
       * 워크스페이스 이름
       * @description 워크스페이스를 대표하는 이름
       * @example My Workspace
       */
      title?: string;
    };
    UserEntity: {
      /**
       * 삭제일
       * Format: date-time
       * @description 삭제일
       */
      deletedAt: string;
      /**
       * 이메일
       * @description 사용자 이메일
       * @example test@naver.com
       */
      email: string;
      /**
       * 이메일 확인 일시
       * Format: date-time
       * @description 이메일 확인 일시
       */
      emailConfirmedAt?: string;
      /**
       * ID
       * @description 사용자 ID
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      id: string;
      /**
       * 정지 여부
       * @description 정지 여부
       * @example false
       */
      isSuspended: boolean;
      /** @description 역할 */
      Role: components["schemas"]["RoleEntity"];
      /**
       * 이름
       * @description 사용자 이름
       * @example 홍길동
       */
      username: string;
      /** @description 프로필 */
      UserProfile: components["schemas"]["UserProfileEntity"];
    };
    UserProfileEntity: {
      /**
       * 이미지
       * @description 프로필 이미지
       */
      image: string;
    };
    UserResponseDto: {
      /** @description 데이터 응답 */
      data: components["schemas"]["UserEntity"];
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    ValidationErrorDto: {
      /** @description Custom Validation Error Response DTO */
      error: components["schemas"]["ValidationExceptionResponseDto"];
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    ValidationExceptionResponseDto: {
      /**
       * @description 에러명
       * @enum {string}
       */
      error:
        | "BadRequestException"
        | "ForbiddenException"
        | "NotFoundException"
        | "UnauthorizedException"
        | "NotAcceptableException"
        | "RequestTimeoutException"
        | "ConflictException"
        | "GoneException"
        | "HttpVersionNotSupportedException"
        | "PayloadTooLargeException"
        | "UnsupportedMediaTypeException"
        | "UnprocessableEntityException"
        | "InternalServerErrorException"
        | "NotImplementedException"
        | "ImATeapotException"
        | "MethodNotAllowedException"
        | "BadGatewayException"
        | "ServiceUnavailableException"
        | "GatewayTimeoutException"
        | "PreconditionFailedException"
        | "ThrottlerException";
      /** @description 에러메시지 */
      message: string;
      /**
       * @description 필드 : [에러정보] 형식의 에러정보가 담긴 객체입니다.
       * @example {
       *       "fieldName": [
       *         "errorinfoOfString"
       *       ]
       *     }
       */
      validationErrorInfo: Record<string, never>;
    };
    WidgetWorkspaceListDto: {
      /** @description 데이터 목록 */
      favoriteWorkspaces: components["schemas"]["WorkspaceEntity"][];
      /** @description 데이터 목록 */
      workspaces: components["schemas"]["WorkspaceEntity"][];
    };
    WidgetWorkspaceListResponseDto: {
      /** @description 데이터 응답 */
      data: components["schemas"]["WidgetWorkspaceListDto"];
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    WorkspaceDeleteResponseDto: {
      /** @description 데이터 응답 */
      data: boolean;
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    WorkspaceDetailResponseDto: {
      /** @description 데이터 응답 */
      data: components["schemas"]["WorkspaceEntity"];
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    WorkspaceEntity: {
      /**
       * Format: date-time
       * @description 생성일
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description 삭제일
       */
      deletedAt?: string | null;
      /** @description 워크스페이스 설명 */
      description?: string | null;
      /** @description 워크스페이스 ID */
      id: number;
      /** @description 즐겨찾기 여부 */
      isFavorite: boolean;
      /** @description 순서 */
      order: number;
      /** @description 워크스페이스 이름 */
      title: string;
      /**
       * Format: date-time
       * @description 수정일
       */
      updatedAt: string;
    };
    WorkspaceListResponseDto: {
      /** @description 데이터 응답 */
      data: components["schemas"]["WorkspacePaginationListDto"];
      /**
       * @description 결과 코드
       * @enum {number}
       */
      resultCode:
        | 1
        | -1
        | 1001
        | 1002
        | 1003
        | 1004
        | 1005
        | 4001
        | 4002
        | 6001
        | 6002
        | 6003
        | 6004
        | 6005
        | 7000
        | 7001;
      /**
       * @description 상태코드
       * @enum {number}
       */
      statusCode:
        | 100
        | 101
        | 102
        | 103
        | 200
        | 201
        | 202
        | 203
        | 204
        | 205
        | 206
        | 300
        | 301
        | 302
        | 303
        | 304
        | 307
        | 308
        | 400
        | 401
        | 402
        | 403
        | 404
        | 405
        | 406
        | 407
        | 408
        | 409
        | 410
        | 411
        | 412
        | 413
        | 414
        | 415
        | 416
        | 417
        | 418
        | 421
        | 422
        | 424
        | 428
        | 429
        | 500
        | 501
        | 502
        | 503
        | 504
        | 505;
    };
    WorkspacePaginationListDto: {
      /** @description 데이터 목록 */
      list: components["schemas"]["WorkspaceEntity"][];
      /** @description 페이지 정보 */
      pageInfo: components["schemas"]["PageInfoDto"];
      /** @description 전체 데이터 수 */
      totalCount: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogoutResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  AuthController_signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 로그인 API */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInDTO"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["HttpErrorDto"]
            | components["schemas"]["ValidationErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  AuthController_signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 회원가입 API */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpDTO"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["HttpErrorDto"]
            | components["schemas"]["ValidationErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  AuthController_token: {
    parameters: {
      query: {
        /**
         * @description 검증 타입
         * @example refresh_token
         */
        grantType: "refresh_token";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 토큰 재발급 API */
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenDTO"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["HttpErrorDto"]
            | components["schemas"]["ValidationErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description 사용자 정보 변경 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["HttpErrorDto"]
            | components["schemas"]["ValidationErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  UsersController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  WidgetsController_findAllByWidgetWorkspace: {
    parameters: {
      query?: {
        /** @description 페이지 크기 */
        limit?: number;
        /** @description 정렬 순서 */
        sortOrder?: "asc" | "desc" | null;
        /** @description 정렬 기준 */
        sortTag?: "createdAt" | "updatedAt" | "order" | null;
        /** @description 작업공간 제목 검색 */
        title?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WidgetWorkspaceListResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  WorkspacesController_findManyByDeleted: {
    parameters: {
      query?: {
        /**
         * @description 즐겨찾기
         * @example [
         *       "true",
         *       "false"
         *     ]
         */
        favorites?: string[] | null;
        /** @description 페이지 크기 */
        limit?: number;
        /** @description 페이지 번호 */
        pageNo?: number | null;
        /** @description 정렬 순서 */
        sortOrder?: "asc" | "desc" | null;
        /** @description 정렬 기준 */
        sortTag?: "createdAt" | "updatedAt" | "order" | null;
        /** @description 작업공간 제목 검색 */
        title?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceListResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  WorkspacesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceDetailResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["HttpErrorDto"]
            | components["schemas"]["ValidationErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  WorkspacesController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceDetailResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  WorkspacesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceDeleteResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  WorkspacesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkspaceDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceDetailResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["HttpErrorDto"]
            | components["schemas"]["ValidationErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
  WorkspacesController_favorite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FavoriteWorkspaceDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkspaceDetailResponseDto"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["HttpErrorDto"]
            | components["schemas"]["ValidationErrorDto"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HttpErrorDto"];
        };
      };
    };
  };
}
