packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.53.3
  "@tanstack/svelte-query": ^5.53.3
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  superjson: ^2.2.1
  zod: ^3.23.8
  date-fns: ^3.6.0
  "@t3-oss/env-core": "^0.11.0"
  "react-hook-form": "^7.53.0"
  "@hookform/resolvers": "^3.9.0"
  zustand: "^4.5.4"

  eslint: ^9.9.1
  prettier: ^3.3.3
  typescript: ^5.5.4
  rimraf: ^6.0.1
  vite: ^5.4.2
  tsup: ^8.2.4
  tailwindcss: ^3.4.10
  postcss: ^8.4.44
  autoprefixer: ^10.4.20
  tsx: "^4.19.0"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.5
    "@types/react-dom": ^18.3.0
  prisma5:
    prisma: 5.19.1
    "@prisma/client": 5.19.1
