packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.51.9
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  superjson: ^2.2.1
  zod: ^3.23.8
  date-fns: ^3.6.0
  "@t3-oss/env-core": "^0.11.0"
  "react-hook-form": "^7.52.2"
  "@hookform/resolvers": "^3.9.0"
  zustand: "^4.5.4"

  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  rimraf: ^5.0.7
  vite: ^5.3.3
  tsup: ^8.1.0
  tailwindcss: ^3.4.4
  postcss: ^8.4.39
  autoprefixer: ^10.4.19
  tsx: "^4.16.2"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  prisma5:
    prisma: 5.18.0
    "@prisma/client": 5.18.0
  next14:
    next: "^14.2.5"
  kit2:
    "@sveltejs/kit": "^2.5.21"
  remix2:
    "@remix-run/node": "^2.11.1"
    "@remix-run/react": "^2.11.1"
    "@remix-run/serve": "^2.11.1"
    "@remix-run/dev": "^2.11.1"
