packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8
  rimraf: ^5.0.7
  vite: ^5.3.3
  tsup: ^8.1.0
  tailwindcss: ^3.4.4
  postcss: ^8.4.39
  date-fns: ^3.6.0
  autoprefixer: ^10.4.19

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
