packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.62.0
  "@tanstack/react-table": ^8.20.5
  "@tanstack/react-virtual": ^3.10.9
  "@t3-oss/env-core": "^0.11.1"
  "react-hook-form": "^7.53.2"
  "@hookform/resolvers": "^3.9.1"
  zustand: "^5.0.1"
  zod: ^3.23.8
  date-fns: ^3.6.0
  uncrypto: ^0.1.3

  eslint: ^9.9.1
  prettier: ^3.3.3
  typescript: ^5.7.2
  vite: ^6.0.3
  tsup: ^8.2.4
  tailwindcss: ^3.4.10
  postcss: ^8.4.44
  autoprefixer: ^10.4.20
  tsx: "^4.19.0"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.5
    "@types/react-dom": ^18.3.0
  prisma5:
    prisma: 6.0.0
    "@prisma/client": 6.0.0
  remix2:
    "@remix-run/node": "^2.15.2"
    "@remix-run/react": "^2.15.2"
    "@remix-run/serve": "^2.15.2"
    "@remix-run/dev": "^2.15.2"
  lodash:
    lodash-es: ^4.17.21
    "@types/lodash-es": "^4.17.12"
  openapi:
    "openapi-fetch": "^0.13.0"
    "openapi-typescript-helpers": "^0.0.15"
