// Generated by Wrangler on Fri May 03 2024 01:53:34 GMT+0900 (대한민국 표준시)
// by running `wrangler types`

interface Env {
	cache: KVNamespace;
	COOKIE_SESSION_SECRET: string;
	TOAST_SECRET: string;
	SIGN_MESSAGE: string;
	THEME_SECRET: string;
}
